kind: pipeline
type: exec
name: default

steps:
  - name: frontend_build
    depends_on:
      - clone
    commands:
      - cd nextjs
      - npm install
      - npm run build
      - cd ..

  - name: frontend_deploy
    depends_on:
      - frontend_build
    commands:
      - sudo rm -rf /var/lib/static-site-server-rs/sites/site_css_reliability
      - sudo mkdir -p /var/lib/static-site-server-rs/sites/site_css_reliability/files
      - sudo install -m 644 -T nextjs/site.yaml /var/lib/static-site-server-rs/sites/site_css_reliability/site.yaml
      - sudo cp -R nextjs/out/. /var/lib/static-site-server-rs/sites/site_css_reliability/files/.

  - name: frontent_reload
    depends_on:
      - frontend_deploy
    commands:
      - sudo touch /var/lib/static-site-server-rs/routes.yaml

  - name: copy
    depends_on:
      - clone
    environment:
      SHARED_SOLUTION_KEY:
        from_secret: shared_solution_key
    commands:
      - sudo mkdir -p /var/www/css_reliability
      - sudo rm -rf /var/www/css_reliability/client-snpshtr.py
      - sudo mkdir -p /var/www/css_reliability/virtual_env
      - sudo mv /var/www/css_reliability/virtual_env /var/www/css_reliability/virtual_env_
      - sudo cp server-snpshtr.py /var/www/css_reliability/server-snpshtr.py
      - sudo cp cronform.html /var/www/css_reliability/cronform.html
      - sudo cp requirements.txt /var/www/css_reliability/requirements.txt
      - sudo cp Makefile /var/www/css_reliability/Makefile
      - sudo make -C /var/www/css_reliability virtual_env
      - sudo rm -rf /var/www/css_reliability/virtual_env_
      - echo $$SHARED_SOLUTION_KEY | sudo tee /var/www/css_reliability/apikey.txt >/dev/null
      - sudo mkdir -p /var/www/css_reliability/docker
      - sudo chown http:http -R /var/www/css_reliability

  - name: configure
    depends_on:
      - copy
    commands:
      - cat srvconfig/nginx.conf | sed -e 's/{domain}/api-css-reliability.sfner.com/g' -e 's/{port}/35795/g' -e 's/{path}/\\/var\\/www\\/css_reliability/g' | sudo tee /etc/nginx/sites-available/api-css-reliability-sfner-com-http.conf > /dev/null
      - cat srvconfig/nginx-nomedia.conf | sed -e 's/{domain}/test-api-css-reliability.sfner.com/g' -e 's/{port}/35796/g' | sudo tee /etc/nginx/sites-available/test-api-css-reliability-sfner-com-http.conf > /dev/null
      - cat srvconfig/systemd.service | sed -e 's/{name}/api-css-reliability.sfner.com/g' -e 's/{port}/35795/g' -e 's/{path}/\\/var\\/www\\/css_reliability/g' -e 's/{verb}/serve/g' | sudo tee /etc/systemd/system/css_reliability.service > /dev/null

  - name: restart
    depends_on:
      - configure
    commands:
      - sudo systemctl daemon-reload
      - sudo systemctl reload nginx
      - sudo systemctl enable css_reliability.service
      - sudo systemctl restart css_reliability.service

  - name: docker_cmp_imsave
    depends_on:
      - copy
    environment:
      SHARED_SOLUTION_KEY:
        from_secret: shared_solution_key
    commands:
      - sudo docker build . -f docker-client-snpcmp.Dockerfile -t docker-client-snpcmp --build-arg apikey=$$SHARED_SOLUTION_KEY --build-arg baseapi=https://api-css-reliability.sfner.com
      - sudo docker image save -o /var/www/css_reliability/docker/docker-client-snpcmp.tar docker-client-snpcmp
      - sudo chown http:http -R /var/www/css_reliability/docker
      - echo docker run -itd --hostname linux-docker --restart always --name docker-client-snpcmp docker-client-snpcmp:latest

  - name: docker_shtr_imsave
    depends_on:
      - copy
    environment:
      SHARED_SOLUTION_KEY:
        from_secret: shared_solution_key
    commands:
      - sudo docker build . -f docker-client-dckshtr.Dockerfile -t docker-client-dckshtr --build-arg apikey=$$SHARED_SOLUTION_KEY --build-arg baseapi=https://api-css-reliability.sfner.com
      - sudo docker image save -o /var/www/css_reliability/docker/docker-client-dckshtr.tar docker-client-dckshtr
      - sudo chown http:http -R /var/www/css_reliability/docker
      - echo docker run -itd --hostname linux-docker --restart always --name docker-client-dckshtr docker-client-dckshtr:latest
